### ISSUE TITLE
'num_repeats' not defined during skill discovery

### ISSUE THREAD

**Issue by SiyuanLee** [jaekyeom/IBOL#1]
Hi,

Thanks for publishing the code. In the skill discovery training stage, there is a bug of missing _'num_repeats'_ in Line 88 of _''garagei/envs/child_policy_env.py"_, which should have been defined in Line 190 of _"tests/main.py"._  

I search the repo, and find that _'num_repeats'_ has a default value of 1. Is that a suitable value for skill discovery? Which variable does it correspond to in the paper?

Looking forward to your reply! Thanks!

**Comment by jaekyeom** [comment]
Hi,
Thank you for showing an interest in our work!

`num_repeats` is an unused hyperparameter (it can be set to 1), which we didn't remove during the code clean-up process.

Thanks for reporting the issue.
We've updated our code accordingly, and it should be fixed now.
