### ISSUE TITLE
Has anyone debug the code and get straight skill path?

### ISSUE THREAD

**Issue by www2171668** [jaekyeom/IBOL#2]
Did anyone debug this code and get the diversity path as shown in the paper? I don't seem to get that effect. I used a diayn code and I can barely run the skill diversity path as shown in the paper. I just want to know if you can get a straight path like that? It really helps me.!!!
![image](https://user-images.githubusercontent.com/49861957/168110314-e9604ecb-c31e-44d7-a011-0344f59eb40b.png)

**Comment by jaekyeom** [comment]
Hi,
Thanks for your interest in our work!

I'd like to make sure that we are on the same page.
By "a straight path", do you mean the image on the left in your screenshot?
If so, then please note that it is the result of IBOL, and you would need to use our code to reproduce that.

In case you have any further questions, please feel free to re-open this issue or leave a comment!
